### ISSUE TITLE
Please Support Cartege !! 

### ISSUE THREAD

**Issue by yong076** [EightyThreeCreative/ShineUpdater#1]
please... :)

**Comment by maxawad** [comment]
What is Cartege?

**Comment by Vortec4800** [comment]
I have no problem supporting Carthage, though as I don't use it myself I'm not sure how it needs to be set up or know if it's working properly. If somebody would like to configure everything and send in a PR, I'd be more than happy to take a look and merge it to add support.

**Comment by mccallus** [comment]
@Vortec4800 all that's required is to share the Xcode scheme, https://github.com/Carthage/Carthage#share-your-xcode-schemes. I've tested this locally and it worked without issue.
