### ISSUE TITLE
Shine: Error downloading Feed: This node is invalid:

### ISSUE THREAD

**Issue by lexcellence** [EightyThreeCreative/ShineUpdater#10]
I got this error message, does it mean there is something wrong with my xml description? 
Or I cannnot use the dropbox public link?

 Shine.shared.setup { config in
            config.feedURL = URL(string: "https://www.dropbox.com/s/xxxxxxxxxxx/Appcast.xml?dl=0")!                        
        }

**Comment by Vortec4800** [comment]
That error means it can't parse the XML at your feed URL. I'm not sure if that's because Dropbox isn't serving the raw file and putting some extra stuff in the file the parser doesn't understand, or if there is an actual error in your XML file, but that's what is happening.

**Comment by lexcellence** [comment]
> That error means it can't parse the XML at your feed URL. I'm not sure if that's because Dropbox isn't serving the raw file and putting some extra stuff in the file the parser doesn't understand, or if there is an actual error in your XML file, but that's what is happening.

I tried using google dirve, but i still got the same error.
I also tried to use the XML file from the example, i got the error again.
Maybe i cannot use dropbox or google drive as HTTPs file server.

Is there anything wrong with my XML or plist file?
1.XML file
https://drive.google.com/open?id=1K0Y41y1PGE0C0FLz_A9Ga9MGkPDHR2eA
2. plist file
https://drive.google.com/open?id=1ksRZdYndEwchlUPQvR7Q-FKSeycSvPXv

**Comment by lexcellence** [comment]
Is there anything wrong with my Appcast.xml?

<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:shine="http://www.eightythreecreative.com/shinens" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <channel>
        <title>Initial Release</title>
        <description>Most recent changes with links to updates.</description>
        <language>en</language>
	<item>
            <title>Version 1.0</title>
            <description><![CDATA[• Initial release]]></description>
            <pubDate>Tue, 10 April 2018 10:01:11 -0600</pubDate>
            <enclosure url="https://drive.google.com/open?id=xxxxxxxxx"
                       sparkle:version="6213"
                       sparkle:shortVersionString="0.2" />
            <sparkle:minimumSystemVersion>10.3</sparkle:minimumSystemVersion>
        </item>
        <item>
            <title>Version 2.0</title>
            <description><![CDATA[
• New "Auto Update" Function
• Bugs Fixed]]></description>
            <pubDate>Thu, 24 Oct 2019 10:01:11 +0800</pubDate>
            <enclosure url="https://drive.google.com/open?id=xxxxxxxxx"
                       sparkle:version="6476"
                       sparkle:shortVersionString="0.5" />
            <sparkle:minimumSystemVersion>10.3</sparkle:minimumSystemVersion>
            <shine:forcedUpdate />
        </item>
        </channel>
</rss>

**Comment by Vortec4800** [comment]
Your XML looks good but you can't host it like that. All the other contents of the page like the Google download buttons, etc all get picked up by the library and it can't read it. You'll need to host the raw file somewhere.

**Comment by lexcellence** [comment]
Hi Vortec:
Thanks for your reply
I've generated the direct file link, but it still doesnt work. 
Is there anything wrong?
1. XML file
https://drive.google.com/uc?export=download&id=1K0Y41y1PGE0C0FLz_A9Ga9MGkPDHR2eA
2. plist file
https://drive.google.com/uc?export=download&id=1ksRZdYndEwchlUPQvR7Q-FKSeycSvPXv

**Comment by Vortec4800** [comment]
Is it giving you the same error as before? Or a different one?

**Comment by Vortec4800** [comment]
I did some digging, it looks like the Google Drive URLs in the `enclosure` tag is screwing with the parser. If you run it through some online XML validators, it fails there as well. You may be able to URL-encode those values to get it to work. It may be more reliable to host these from something like an S3 bucket instead, and use the public URL from there, but the Google Drive URL seems to be where your problem is.

**Comment by lexcellence** [comment]
> I did some digging, it looks like the Google Drive URLs in the `enclosure` tag is screwing with the parser. If you run it through some online XML validators, it fails there as well. You may be able to URL-encode those values to get it to work. It may be more reliable to host these from something like an S3 bucket instead, and use the public URL from there, but the Google Drive URL seems to be where your problem is.

Hi Vortec:
I do really appreciate for your reply.
I tried URL-encode on google drive URL, but it doesnt work.
Then I tried S3 bucket, it works perfectly.
You save my life. 
Thanks

Alex
