### ISSUE TITLE
SWXMLHash is low version that can't build new Xcode Server

### ISSUE THREAD

**Issue by PeiCinh** [EightyThreeCreative/ShineUpdater#9]
When build on Xcode server will error.
the messgae is 
Error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'SWXMLHash')

**Comment by Vortec4800** [comment]
Sorry for the wait. We just released pod version 1.3 which fixes this.
